### ISSUE TITLE
Create a pip requirements file

### ISSUE THREAD

**Issue by someshsingh22** [cte-bits-goa/Certificate_Generator#1]
In future, we will make this a small python library so that all it takes is 3 lines of code to run a massive script else someone might use an environment to do this currently you need three libraries to be installed before you can use this mak a pip requirements file that automatically installs all required libraries.

current dependencies :
Pandas, Numpy, PIL

Learn how to make these requirement files [here](https://medium.com/@boscacci/why-and-how-to-make-a-requirements-txt-f329c685181e) 👍

**Comment by kdarsh17** [comment]
Im taking it up

**Comment by someshsingh22** [comment]
Great!
