### ISSUE TITLE
Convert the process to vectorized Image format

### ISSUE THREAD

**Issue by someshsingh22** [cte-bits-goa/Certificate_Generator#4]
For enabling this script to be a part of our website we want to shift to vector image format. Implement the changes for that.

What is the vector format > [Vector Image Format](https://www.geeksforgeeks.org/vector-vs-raster-graphics/)
An easy tool for this > [gizeh](https://github.com/Zulko/gizeh)

**Comment by shwetabh15** [comment]
Working on this
