### ISSUE TITLE
Web Scraper

### ISSUE THREAD

**Issue by someshsingh22** [cte-bits-goa/Certificate_Generator#5]
To ensure that IDs use the official name as on SWD, we extract the names from SWD by searching the BITS IDs, There is a perfectly working script for the older website but now that the website has changed we need to modify the script to shift it to the new website.

**Comment by SuhrudhSarathy** [comment]
I am working on this

**Comment by someshsingh22** [comment]
@SuhrudhSarathy What's the progress? I am updating the requirements to annual use, the SWD HTML can be downloaded manually

The new process will be given an HTML file to generate a CSV of students and IDs

**Comment by SuhrudhSarathy** [comment]
The SWD Scrapper was separated out as a standalone repository. It is capable of scrapping from the swd website directly. 

This new worflow can ve made to work by modifying the existing one.

**Comment by SuhrudhSarathy** [comment]
Updated Scraper for the SWD website

https://github.com/cte-bits-goa/SWD-Scraper

**Comment by someshsingh22** [comment]
Ok so I am closing the issue here and shifting it there. https://github.com/cte-bits-goa/SWD-Scraper/issues/1
