### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by someshsingh22** [cte-bits-goa/Certificate_Generator#6]
Create a logger so that if the script breaks in between you know the current position, Right now we are managing it by printing the last created on the terminal but if someone accidentally closes his terminal/switches off he will lose progress.

Know about logging [here](https://www.geeksforgeeks.org/logging-in-python/)

**Comment by SuhrudhSarathy** [comment]
I will work on this issue

**Comment by SuhrudhSarathy** [comment]
Please check #7 for the changes
